spring:
  application:
    name: order-ms

  config:
    import: configserver:${CONFIG_SERVER_HOST:http://127.0.0.1:8080}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'